services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2025-latest
    container_name: swiftorder-sqlserver
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=${SA_PASSWORD}
      - MSSQL_PID=${MSSQL_PID}
    ports:
      - "1433:1433"
    volumes:
      - swiftorder_sqlserver_data:/var/opt/mssql
    restart: unless-stopped

  rabbitmq:
    image: rabbitmq:3-management
    container_name: swiftorder-rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - swiftorder_rabbitmq_data:/var/lib/rabbitmq
    restart: unless-stopped

volumes:
  swiftorder_sqlserver_data:
  swiftorder_rabbitmq_data: